<?php
$pageTitle = 'Generate License - ' . SITE_NAME;
$errors = get_validation_errors();

$users = Database::fetchAll("SELECT id, name, email FROM users WHERE is_active = 1 ORDER BY name");
$plugins = Database::fetchAll("SELECT id, name FROM plugins WHERE is_active = 1 ORDER BY name");

if ($method === 'POST') {
    require_csrf();
    $userId = (int)($_POST['user_id'] ?? 0);
    $pluginId = (int)($_POST['plugin_id'] ?? 0);
    $licenseType = $_POST['license_type'] ?? 'monthly';
    $customDays = (int)($_POST['custom_days'] ?? 0);
    $maxActivations = (int)($_POST['max_activations'] ?? DEFAULT_MAX_ACTIVATIONS);
    $notes = trim($_POST['notes'] ?? '');

    $errs = [];
    if (!$userId) $errs['user_id'] = 'Select a user.';
    if (!$pluginId) $errs['plugin_id'] = 'Select a plugin.';
    if (!in_array($licenseType, ['monthly', 'yearly', 'lifetime', 'custom_days'])) $errs['license_type'] = 'Invalid license type.';
    if ($licenseType === 'custom_days' && $customDays < 1) $errs['custom_days'] = 'Enter number of days.';

    if (!empty($errs)) {
        set_validation_errors($errs);
        set_old_input($_POST);
        redirect('/admin/licenses/create');
    }

    $licenseKey = LicenseKeyGenerator::generate($pluginId);
    $expiresAt = LicenseKeyGenerator::calculateExpiration($licenseType, $customDays ?: null);

    Database::insert('licenses', [
        'user_id' => $userId,
        'plugin_id' => $pluginId,
        'order_id' => null,
        'license_key' => $licenseKey,
        'license_type' => $licenseType,
        'custom_days' => $licenseType === 'custom_days' ? $customDays : null,
        'status' => 'active',
        'starts_at' => date('Y-m-d H:i:s'),
        'expires_at' => $expiresAt,
        'max_activations' => $maxActivations,
        'current_activations' => 0,
        'notes' => $notes ? 'Manually generated. ' . $notes : 'Manually generated by admin.',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
    ]);

    set_flash('success', 'License generated: ' . $licenseKey);
    redirect('/admin/licenses');
}

require BASE_PATH . '/includes/admin-header.php';
?>

<div class="mb-6">
    <a href="/admin/licenses" class="text-sm text-gray-400 hover:text-white transition flex items-center gap-1 mb-2">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg> Back to Licenses
    </a>
    <h1 class="text-2xl font-bold text-white">Generate License Manually</h1>
</div>

<form method="POST" action="/admin/licenses/create" class="space-y-6 max-w-2xl">
    <?= csrf_field() ?>
    <div class="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">User *</label>
            <select name="user_id" required class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition">
                <option value="">Select user...</option>
                <?php foreach ($users as $u): ?>
                <option value="<?= $u['id'] ?>" <?= old('user_id') == $u['id'] ? 'selected' : '' ?>><?= e($u['name']) ?> (<?= e($u['email']) ?>)</option>
                <?php endforeach; ?>
            </select>
            <?php if (!empty($errors['user_id'])): ?><p class="mt-1 text-sm text-red-400"><?= e($errors['user_id']) ?></p><?php endif; ?>
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">Plugin *</label>
            <select name="plugin_id" required class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition">
                <option value="">Select plugin...</option>
                <?php foreach ($plugins as $p): ?>
                <option value="<?= $p['id'] ?>" <?= old('plugin_id') == $p['id'] ? 'selected' : '' ?>><?= e($p['name']) ?></option>
                <?php endforeach; ?>
            </select>
            <?php if (!empty($errors['plugin_id'])): ?><p class="mt-1 text-sm text-red-400"><?= e($errors['plugin_id']) ?></p><?php endif; ?>
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">License Type *</label>
            <select name="license_type" required class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition">
                <option value="monthly" <?= old('license_type') === 'monthly' ? 'selected' : '' ?>>Monthly</option>
                <option value="yearly" <?= old('license_type') === 'yearly' ? 'selected' : '' ?>>Yearly</option>
                <option value="lifetime" <?= old('license_type') === 'lifetime' ? 'selected' : '' ?>>Lifetime</option>
                <option value="custom_days" <?= old('license_type') === 'custom_days' ? 'selected' : '' ?>>Custom Days</option>
            </select>
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">Custom Days (if applicable)</label>
            <input type="number" name="custom_days" value="<?= old('custom_days', '30') ?>" min="1" class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition">
            <?php if (!empty($errors['custom_days'])): ?><p class="mt-1 text-sm text-red-400"><?= e($errors['custom_days']) ?></p><?php endif; ?>
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">Max Device Activations</label>
            <input type="number" name="max_activations" value="<?= old('max_activations', (string)DEFAULT_MAX_ACTIVATIONS) ?>" min="1" class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-300 mb-1.5">Notes</label>
            <textarea name="notes" rows="2" class="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white focus:outline-none focus:border-brand-500 transition"><?= old('notes') ?></textarea>
        </div>
    </div>
    <div class="flex items-center gap-4">
        <button type="submit" class="px-8 py-3 bg-brand-600 hover:bg-brand-500 text-white font-semibold rounded-xl transition">Generate License</button>
        <a href="/admin/licenses" class="px-8 py-3 bg-gray-800 hover:bg-gray-700 text-gray-300 font-medium rounded-xl transition">Cancel</a>
    </div>
</form>

<?php
clear_old_input();
require BASE_PATH . '/includes/admin-footer.php';
?>
